---
# Rol de Prerrequisitos. Aplica a Master, Worker01, Worker02 y Nfs.

  # En entorno local he introducido los parámetros de /etc/hosts de forma manual.

  # En entorno MS AZURE introduzco estos parámetros de forma automática a través de Ansible.
  
  - name: Añadir los equipos a fichero /etc/hosts
    lineinfile: 
      path: /etc/hosts
      state: present
      line: "{{ item }}"
    with_items:
    - '10.0.1.10 master.victor.com'
    - '10.0.1.11 nfs.victor.com'
    - '10.0.1.12 worker01.victor.com'
    - '10.0.1.13 worker02.victor.com'
  
  
  - name: Instalar el demonio chrony en CentOS
    package:
      name: 
       - chrony
      state: latest
  
  - name: Arrancar y habilitar el servicio chronyd
    systemd: 
      name: chronyd
      state: started
      daemon_reload: yes
      enabled: yes
      
  - name: Seleccionar la zona horaria Europe/Madrid
    timezone:
      name: Europe/Madrid
  
  - name: Habilitar el servicio ntp
    command: /usr/bin/timedatectl set-ntp true

  - name: Deshabilitar SELinux
    selinux:
      state: disabled

  - name: Activar Firewall
    systemd:
      name: firewalld 
      state: started
      enabled: yes

  - name: Actualizar paquetes 
    dnf:
      name: "*"
      state: latest

  - name: Instalación de paquetes para el rol de NFS
    dnf:
      name:
        - nfs-utils
        - nfs4-acl-tools
        - wget
      state: latest

  - name: Reiniciar todas las máquinas virtuales para aplicar la nueva configuración de SELinux
    reboot:
      reboot_timeout: 5