--- 

# Rol de NFS. Aplica solo al servidor de NFS.

  - name: Creando directorio para NFS
    file:
      path: /srv/nfs
      state: directory
      owner: victor
      group: victor
      mode: 0777
  
  - name: Instalando paquetes para NFS 
    dnf:
      name:
        - net-tools
        - nfs-utils
      state: latest

  - name: Arrancar y habilitar servicio NFS
    systemd: 
      name: nfs-server
      state: started
      daemon_reload: yes
      enabled: yes

  - name: Añadir líneas al archivo export
    lineinfile:
      path: /etc/exports
      state: present
      line: "{{ item }}"
    with_items:
    
    # IPs entorno local
    #- '/srv/nfs  192.168.1.102(rw,sync)' # master
    #- '/srv/nfs  192.168.1.108(rw,sync)' # worker01
    #- '/srv/nfs  192.168.1.109(rw,sync)' # worker02
    
    # IPs entorno AZURE

    - '/srv/nfs  10.0.1.10(rw,sync)' # master
    - '/srv/nfs  10.0.1.12(rw,sync)' # worker01
    - '/srv/nfs  10.0.1.13(rw,sync)' # worker02

  - name: Ejecutar exportfs -r
    command: exportfs -r
  
  - name: execute exportfs -s
    command: exportfs -s

  - name: Añadir los puertos correspondientes en Firewalld
    firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
    with_items: 
      - "nfs"
      - "rpc-bind"
      - "mountd"